/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as interfaces from "./interfaces";

export type { interfaces };
export type { UniswapV2ERC20 } from "./UniswapV2ERC20";
