/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20Interface } from "./Erc20Interface";
export type { UniswapV2Pair } from "./UniswapV2Pair";
