/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20 } from "./Erc20";
export type { Erc20Permit } from "./Erc20Permit";
export type { Erc20Recover } from "./Erc20Recover";
export type { IErc20 } from "./IErc20";
export type { IErc20Permit } from "./IErc20Permit";
export type { IErc20Recover } from "./IErc20Recover";
