/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as math from "./math";
import type * as test from "./test";

export type { math };

export type { test };
export type { HifiPool } from "./HifiPool";
export type { HifiPoolRegistry } from "./HifiPoolRegistry";
export type { IHifiPool } from "./IHifiPool";
export type { IHifiPoolRegistry } from "./IHifiPoolRegistry";
