/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IHifiProxyTargetInterface extends utils.Interface {
  functions: {
    "borrowHTokenAndBuyUnderlying(address,address,uint256,uint256)": FunctionFragment;
    "buyHTokenAndRepayBorrow(address,address,uint256,uint256)": FunctionFragment;
    "buyHTokenAndRepayBorrowWithSignature(address,address,uint256,uint256,uint256,bytes)": FunctionFragment;
    "depositCollateral(address,address,uint256)": FunctionFragment;
    "depositCollateralWithSignature(address,address,uint256,uint256,bytes)": FunctionFragment;
    "depositUnderlyingAndMintHTokenAndAddLiquidity(address,uint256,uint256)": FunctionFragment;
    "depositUnderlyingAndMintHTokenAndAddLiquidityWithSignature(address,uint256,uint256,uint256,bytes)": FunctionFragment;
    "depositUnderlyingAndRepayBorrow(address,address,uint256)": FunctionFragment;
    "depositUnderlyingAndRepayBorrowWithSignature(address,address,uint256,uint256,bytes)": FunctionFragment;
    "redeem(address,uint256,uint256)": FunctionFragment;
    "redeemWithSignature(address,uint256,uint256,uint256,bytes)": FunctionFragment;
    "removeLiquidity(address,uint256)": FunctionFragment;
    "removeLiquidityAndRedeem(address,uint256)": FunctionFragment;
    "removeLiquidityAndRedeemWithSignature(address,uint256,uint256,bytes)": FunctionFragment;
    "removeLiquidityAndWithdrawUnderlying(address,uint256,uint256)": FunctionFragment;
    "removeLiquidityAndWithdrawUnderlyingWithSignature(address,uint256,uint256,uint256,bytes)": FunctionFragment;
    "removeLiquidityWithSignature(address,uint256,uint256,bytes)": FunctionFragment;
    "sellHToken(address,uint256,uint256)": FunctionFragment;
    "sellHTokenWithSignature(address,uint256,uint256,uint256,bytes)": FunctionFragment;
    "sellUnderlying(address,uint256,uint256)": FunctionFragment;
    "sellUnderlyingAndRepayBorrow(address,address,uint256,uint256)": FunctionFragment;
    "sellUnderlyingAndRepayBorrowWithSignature(address,address,uint256,uint256,uint256,bytes)": FunctionFragment;
    "sellUnderlyingWithSignature(address,uint256,uint256,uint256,bytes)": FunctionFragment;
    "withdrawCollateral(address,address,uint256)": FunctionFragment;
    "withdrawCollateralAndUnwrapWeth(address,address,uint256)": FunctionFragment;
    "wrapEthAndDepositCollateral(address,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "borrowHTokenAndBuyUnderlying"
      | "buyHTokenAndRepayBorrow"
      | "buyHTokenAndRepayBorrowWithSignature"
      | "depositCollateral"
      | "depositCollateralWithSignature"
      | "depositUnderlyingAndMintHTokenAndAddLiquidity"
      | "depositUnderlyingAndMintHTokenAndAddLiquidityWithSignature"
      | "depositUnderlyingAndRepayBorrow"
      | "depositUnderlyingAndRepayBorrowWithSignature"
      | "redeem"
      | "redeemWithSignature"
      | "removeLiquidity"
      | "removeLiquidityAndRedeem"
      | "removeLiquidityAndRedeemWithSignature"
      | "removeLiquidityAndWithdrawUnderlying"
      | "removeLiquidityAndWithdrawUnderlyingWithSignature"
      | "removeLiquidityWithSignature"
      | "sellHToken"
      | "sellHTokenWithSignature"
      | "sellUnderlying"
      | "sellUnderlyingAndRepayBorrow"
      | "sellUnderlyingAndRepayBorrowWithSignature"
      | "sellUnderlyingWithSignature"
      | "withdrawCollateral"
      | "withdrawCollateralAndUnwrapWeth"
      | "wrapEthAndDepositCollateral"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "borrowHTokenAndBuyUnderlying",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "buyHTokenAndRepayBorrow",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "buyHTokenAndRepayBorrowWithSignature",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositCollateral",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositCollateralWithSignature",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositUnderlyingAndMintHTokenAndAddLiquidity",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositUnderlyingAndMintHTokenAndAddLiquidityWithSignature",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositUnderlyingAndRepayBorrow",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositUnderlyingAndRepayBorrowWithSignature",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemWithSignature",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidityAndRedeem",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidityAndRedeemWithSignature",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidityAndWithdrawUnderlying",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidityAndWithdrawUnderlyingWithSignature",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidityWithSignature",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sellHToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sellHTokenWithSignature",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sellUnderlying",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sellUnderlyingAndRepayBorrow",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sellUnderlyingAndRepayBorrowWithSignature",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sellUnderlyingWithSignature",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCollateral",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCollateralAndUnwrapWeth",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "wrapEthAndDepositCollateral",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "borrowHTokenAndBuyUnderlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyHTokenAndRepayBorrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyHTokenAndRepayBorrowWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositCollateralWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositUnderlyingAndMintHTokenAndAddLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositUnderlyingAndMintHTokenAndAddLiquidityWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositUnderlyingAndRepayBorrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositUnderlyingAndRepayBorrowWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "redeemWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidityAndRedeem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidityAndRedeemWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidityAndWithdrawUnderlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidityAndWithdrawUnderlyingWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidityWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellHToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellHTokenWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellUnderlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellUnderlyingAndRepayBorrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellUnderlyingAndRepayBorrowWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellUnderlyingWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCollateralAndUnwrapWeth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrapEthAndDepositCollateral",
    data: BytesLike
  ): Result;

  events: {
    "BorrowHTokenAndBuyUnderlying(address,uint256,uint256)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "BorrowHTokenAndBuyUnderlying"
  ): EventFragment;
}

export interface BorrowHTokenAndBuyUnderlyingEventObject {
  borrower: string;
  borrowAmount: BigNumber;
  underlyingAmount: BigNumber;
}
export type BorrowHTokenAndBuyUnderlyingEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  BorrowHTokenAndBuyUnderlyingEventObject
>;

export type BorrowHTokenAndBuyUnderlyingEventFilter =
  TypedEventFilter<BorrowHTokenAndBuyUnderlyingEvent>;

export interface IHifiProxyTarget extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IHifiProxyTargetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    borrowHTokenAndBuyUnderlying(
      balanceSheet: PromiseOrValue<string>,
      hifiPool: PromiseOrValue<string>,
      maxBorrowAmount: PromiseOrValue<BigNumberish>,
      underlyingOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    buyHTokenAndRepayBorrow(
      hifiPool: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      maxUnderlyingIn: PromiseOrValue<BigNumberish>,
      hTokenOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    buyHTokenAndRepayBorrowWithSignature(
      hifiPool: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      maxUnderlyingIn: PromiseOrValue<BigNumberish>,
      hTokenOut: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositCollateral(
      balanceSheet: PromiseOrValue<string>,
      collateral: PromiseOrValue<string>,
      depositAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositCollateralWithSignature(
      balanceSheet: PromiseOrValue<string>,
      collateral: PromiseOrValue<string>,
      depositAmount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureCollateral: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositUnderlyingAndMintHTokenAndAddLiquidity(
      hifiPool: PromiseOrValue<string>,
      depositAmount: PromiseOrValue<BigNumberish>,
      underlyingOffered: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositUnderlyingAndMintHTokenAndAddLiquidityWithSignature(
      hifiPool: PromiseOrValue<string>,
      depositAmount: PromiseOrValue<BigNumberish>,
      underlyingOffered: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositUnderlyingAndRepayBorrow(
      hToken: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      underlyingAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositUnderlyingAndRepayBorrowWithSignature(
      hToken: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      underlyingAmount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    redeem(
      hToken: PromiseOrValue<string>,
      hTokenAmount: PromiseOrValue<BigNumberish>,
      underlyingAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    redeemWithSignature(
      hToken: PromiseOrValue<string>,
      hTokenAmount: PromiseOrValue<BigNumberish>,
      underlyingAmount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureHToken: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeLiquidity(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeLiquidityAndRedeem(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeLiquidityAndRedeemWithSignature(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureLPToken: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeLiquidityAndWithdrawUnderlying(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      withdrawAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeLiquidityAndWithdrawUnderlyingWithSignature(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      withdrawAmount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureLPToken: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeLiquidityWithSignature(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureLPToken: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sellHToken(
      hifiPool: PromiseOrValue<string>,
      hTokenIn: PromiseOrValue<BigNumberish>,
      minUnderlyingOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sellHTokenWithSignature(
      hifiPool: PromiseOrValue<string>,
      hTokenIn: PromiseOrValue<BigNumberish>,
      minUnderlyingOut: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureHToken: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sellUnderlying(
      hifiPool: PromiseOrValue<string>,
      underlyingIn: PromiseOrValue<BigNumberish>,
      minHTokenOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sellUnderlyingAndRepayBorrow(
      hifiPool: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      underlyingIn: PromiseOrValue<BigNumberish>,
      minHTokenOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sellUnderlyingAndRepayBorrowWithSignature(
      hifiPool: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      underlyingIn: PromiseOrValue<BigNumberish>,
      minHTokenOut: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sellUnderlyingWithSignature(
      hifiPool: PromiseOrValue<string>,
      underlyingIn: PromiseOrValue<BigNumberish>,
      minHTokenOut: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawCollateral(
      balanceSheet: PromiseOrValue<string>,
      collateral: PromiseOrValue<string>,
      withdrawAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawCollateralAndUnwrapWeth(
      weth: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      withdrawAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    wrapEthAndDepositCollateral(
      weth: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  borrowHTokenAndBuyUnderlying(
    balanceSheet: PromiseOrValue<string>,
    hifiPool: PromiseOrValue<string>,
    maxBorrowAmount: PromiseOrValue<BigNumberish>,
    underlyingOut: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  buyHTokenAndRepayBorrow(
    hifiPool: PromiseOrValue<string>,
    balanceSheet: PromiseOrValue<string>,
    maxUnderlyingIn: PromiseOrValue<BigNumberish>,
    hTokenOut: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  buyHTokenAndRepayBorrowWithSignature(
    hifiPool: PromiseOrValue<string>,
    balanceSheet: PromiseOrValue<string>,
    maxUnderlyingIn: PromiseOrValue<BigNumberish>,
    hTokenOut: PromiseOrValue<BigNumberish>,
    deadline: PromiseOrValue<BigNumberish>,
    signatureUnderlying: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositCollateral(
    balanceSheet: PromiseOrValue<string>,
    collateral: PromiseOrValue<string>,
    depositAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositCollateralWithSignature(
    balanceSheet: PromiseOrValue<string>,
    collateral: PromiseOrValue<string>,
    depositAmount: PromiseOrValue<BigNumberish>,
    deadline: PromiseOrValue<BigNumberish>,
    signatureCollateral: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositUnderlyingAndMintHTokenAndAddLiquidity(
    hifiPool: PromiseOrValue<string>,
    depositAmount: PromiseOrValue<BigNumberish>,
    underlyingOffered: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositUnderlyingAndMintHTokenAndAddLiquidityWithSignature(
    hifiPool: PromiseOrValue<string>,
    depositAmount: PromiseOrValue<BigNumberish>,
    underlyingOffered: PromiseOrValue<BigNumberish>,
    deadline: PromiseOrValue<BigNumberish>,
    signatureUnderlying: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositUnderlyingAndRepayBorrow(
    hToken: PromiseOrValue<string>,
    balanceSheet: PromiseOrValue<string>,
    underlyingAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositUnderlyingAndRepayBorrowWithSignature(
    hToken: PromiseOrValue<string>,
    balanceSheet: PromiseOrValue<string>,
    underlyingAmount: PromiseOrValue<BigNumberish>,
    deadline: PromiseOrValue<BigNumberish>,
    signatureUnderlying: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  redeem(
    hToken: PromiseOrValue<string>,
    hTokenAmount: PromiseOrValue<BigNumberish>,
    underlyingAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  redeemWithSignature(
    hToken: PromiseOrValue<string>,
    hTokenAmount: PromiseOrValue<BigNumberish>,
    underlyingAmount: PromiseOrValue<BigNumberish>,
    deadline: PromiseOrValue<BigNumberish>,
    signatureHToken: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeLiquidity(
    hifiPool: PromiseOrValue<string>,
    poolTokensBurned: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeLiquidityAndRedeem(
    hifiPool: PromiseOrValue<string>,
    poolTokensBurned: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeLiquidityAndRedeemWithSignature(
    hifiPool: PromiseOrValue<string>,
    poolTokensBurned: PromiseOrValue<BigNumberish>,
    deadline: PromiseOrValue<BigNumberish>,
    signatureLPToken: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeLiquidityAndWithdrawUnderlying(
    hifiPool: PromiseOrValue<string>,
    poolTokensBurned: PromiseOrValue<BigNumberish>,
    withdrawAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeLiquidityAndWithdrawUnderlyingWithSignature(
    hifiPool: PromiseOrValue<string>,
    poolTokensBurned: PromiseOrValue<BigNumberish>,
    withdrawAmount: PromiseOrValue<BigNumberish>,
    deadline: PromiseOrValue<BigNumberish>,
    signatureLPToken: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeLiquidityWithSignature(
    hifiPool: PromiseOrValue<string>,
    poolTokensBurned: PromiseOrValue<BigNumberish>,
    deadline: PromiseOrValue<BigNumberish>,
    signatureLPToken: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sellHToken(
    hifiPool: PromiseOrValue<string>,
    hTokenIn: PromiseOrValue<BigNumberish>,
    minUnderlyingOut: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sellHTokenWithSignature(
    hifiPool: PromiseOrValue<string>,
    hTokenIn: PromiseOrValue<BigNumberish>,
    minUnderlyingOut: PromiseOrValue<BigNumberish>,
    deadline: PromiseOrValue<BigNumberish>,
    signatureHToken: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sellUnderlying(
    hifiPool: PromiseOrValue<string>,
    underlyingIn: PromiseOrValue<BigNumberish>,
    minHTokenOut: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sellUnderlyingAndRepayBorrow(
    hifiPool: PromiseOrValue<string>,
    balanceSheet: PromiseOrValue<string>,
    underlyingIn: PromiseOrValue<BigNumberish>,
    minHTokenOut: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sellUnderlyingAndRepayBorrowWithSignature(
    hifiPool: PromiseOrValue<string>,
    balanceSheet: PromiseOrValue<string>,
    underlyingIn: PromiseOrValue<BigNumberish>,
    minHTokenOut: PromiseOrValue<BigNumberish>,
    deadline: PromiseOrValue<BigNumberish>,
    signatureUnderlying: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sellUnderlyingWithSignature(
    hifiPool: PromiseOrValue<string>,
    underlyingIn: PromiseOrValue<BigNumberish>,
    minHTokenOut: PromiseOrValue<BigNumberish>,
    deadline: PromiseOrValue<BigNumberish>,
    signatureUnderlying: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawCollateral(
    balanceSheet: PromiseOrValue<string>,
    collateral: PromiseOrValue<string>,
    withdrawAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawCollateralAndUnwrapWeth(
    weth: PromiseOrValue<string>,
    balanceSheet: PromiseOrValue<string>,
    withdrawAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  wrapEthAndDepositCollateral(
    weth: PromiseOrValue<string>,
    balanceSheet: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    borrowHTokenAndBuyUnderlying(
      balanceSheet: PromiseOrValue<string>,
      hifiPool: PromiseOrValue<string>,
      maxBorrowAmount: PromiseOrValue<BigNumberish>,
      underlyingOut: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    buyHTokenAndRepayBorrow(
      hifiPool: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      maxUnderlyingIn: PromiseOrValue<BigNumberish>,
      hTokenOut: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    buyHTokenAndRepayBorrowWithSignature(
      hifiPool: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      maxUnderlyingIn: PromiseOrValue<BigNumberish>,
      hTokenOut: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositCollateral(
      balanceSheet: PromiseOrValue<string>,
      collateral: PromiseOrValue<string>,
      depositAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositCollateralWithSignature(
      balanceSheet: PromiseOrValue<string>,
      collateral: PromiseOrValue<string>,
      depositAmount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureCollateral: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositUnderlyingAndMintHTokenAndAddLiquidity(
      hifiPool: PromiseOrValue<string>,
      depositAmount: PromiseOrValue<BigNumberish>,
      underlyingOffered: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositUnderlyingAndMintHTokenAndAddLiquidityWithSignature(
      hifiPool: PromiseOrValue<string>,
      depositAmount: PromiseOrValue<BigNumberish>,
      underlyingOffered: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositUnderlyingAndRepayBorrow(
      hToken: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      underlyingAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositUnderlyingAndRepayBorrowWithSignature(
      hToken: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      underlyingAmount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    redeem(
      hToken: PromiseOrValue<string>,
      hTokenAmount: PromiseOrValue<BigNumberish>,
      underlyingAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    redeemWithSignature(
      hToken: PromiseOrValue<string>,
      hTokenAmount: PromiseOrValue<BigNumberish>,
      underlyingAmount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureHToken: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeLiquidity(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeLiquidityAndRedeem(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeLiquidityAndRedeemWithSignature(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureLPToken: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeLiquidityAndWithdrawUnderlying(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      withdrawAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeLiquidityAndWithdrawUnderlyingWithSignature(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      withdrawAmount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureLPToken: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeLiquidityWithSignature(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureLPToken: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    sellHToken(
      hifiPool: PromiseOrValue<string>,
      hTokenIn: PromiseOrValue<BigNumberish>,
      minUnderlyingOut: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    sellHTokenWithSignature(
      hifiPool: PromiseOrValue<string>,
      hTokenIn: PromiseOrValue<BigNumberish>,
      minUnderlyingOut: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureHToken: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    sellUnderlying(
      hifiPool: PromiseOrValue<string>,
      underlyingIn: PromiseOrValue<BigNumberish>,
      minHTokenOut: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    sellUnderlyingAndRepayBorrow(
      hifiPool: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      underlyingIn: PromiseOrValue<BigNumberish>,
      minHTokenOut: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    sellUnderlyingAndRepayBorrowWithSignature(
      hifiPool: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      underlyingIn: PromiseOrValue<BigNumberish>,
      minHTokenOut: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    sellUnderlyingWithSignature(
      hifiPool: PromiseOrValue<string>,
      underlyingIn: PromiseOrValue<BigNumberish>,
      minHTokenOut: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawCollateral(
      balanceSheet: PromiseOrValue<string>,
      collateral: PromiseOrValue<string>,
      withdrawAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawCollateralAndUnwrapWeth(
      weth: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      withdrawAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    wrapEthAndDepositCollateral(
      weth: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BorrowHTokenAndBuyUnderlying(address,uint256,uint256)"(
      borrower?: PromiseOrValue<string> | null,
      borrowAmount?: null,
      underlyingAmount?: null
    ): BorrowHTokenAndBuyUnderlyingEventFilter;
    BorrowHTokenAndBuyUnderlying(
      borrower?: PromiseOrValue<string> | null,
      borrowAmount?: null,
      underlyingAmount?: null
    ): BorrowHTokenAndBuyUnderlyingEventFilter;
  };

  estimateGas: {
    borrowHTokenAndBuyUnderlying(
      balanceSheet: PromiseOrValue<string>,
      hifiPool: PromiseOrValue<string>,
      maxBorrowAmount: PromiseOrValue<BigNumberish>,
      underlyingOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    buyHTokenAndRepayBorrow(
      hifiPool: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      maxUnderlyingIn: PromiseOrValue<BigNumberish>,
      hTokenOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    buyHTokenAndRepayBorrowWithSignature(
      hifiPool: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      maxUnderlyingIn: PromiseOrValue<BigNumberish>,
      hTokenOut: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositCollateral(
      balanceSheet: PromiseOrValue<string>,
      collateral: PromiseOrValue<string>,
      depositAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositCollateralWithSignature(
      balanceSheet: PromiseOrValue<string>,
      collateral: PromiseOrValue<string>,
      depositAmount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureCollateral: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositUnderlyingAndMintHTokenAndAddLiquidity(
      hifiPool: PromiseOrValue<string>,
      depositAmount: PromiseOrValue<BigNumberish>,
      underlyingOffered: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositUnderlyingAndMintHTokenAndAddLiquidityWithSignature(
      hifiPool: PromiseOrValue<string>,
      depositAmount: PromiseOrValue<BigNumberish>,
      underlyingOffered: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositUnderlyingAndRepayBorrow(
      hToken: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      underlyingAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositUnderlyingAndRepayBorrowWithSignature(
      hToken: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      underlyingAmount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    redeem(
      hToken: PromiseOrValue<string>,
      hTokenAmount: PromiseOrValue<BigNumberish>,
      underlyingAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    redeemWithSignature(
      hToken: PromiseOrValue<string>,
      hTokenAmount: PromiseOrValue<BigNumberish>,
      underlyingAmount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureHToken: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeLiquidity(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeLiquidityAndRedeem(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeLiquidityAndRedeemWithSignature(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureLPToken: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeLiquidityAndWithdrawUnderlying(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      withdrawAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeLiquidityAndWithdrawUnderlyingWithSignature(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      withdrawAmount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureLPToken: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeLiquidityWithSignature(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureLPToken: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sellHToken(
      hifiPool: PromiseOrValue<string>,
      hTokenIn: PromiseOrValue<BigNumberish>,
      minUnderlyingOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sellHTokenWithSignature(
      hifiPool: PromiseOrValue<string>,
      hTokenIn: PromiseOrValue<BigNumberish>,
      minUnderlyingOut: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureHToken: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sellUnderlying(
      hifiPool: PromiseOrValue<string>,
      underlyingIn: PromiseOrValue<BigNumberish>,
      minHTokenOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sellUnderlyingAndRepayBorrow(
      hifiPool: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      underlyingIn: PromiseOrValue<BigNumberish>,
      minHTokenOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sellUnderlyingAndRepayBorrowWithSignature(
      hifiPool: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      underlyingIn: PromiseOrValue<BigNumberish>,
      minHTokenOut: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sellUnderlyingWithSignature(
      hifiPool: PromiseOrValue<string>,
      underlyingIn: PromiseOrValue<BigNumberish>,
      minHTokenOut: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawCollateral(
      balanceSheet: PromiseOrValue<string>,
      collateral: PromiseOrValue<string>,
      withdrawAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawCollateralAndUnwrapWeth(
      weth: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      withdrawAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    wrapEthAndDepositCollateral(
      weth: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    borrowHTokenAndBuyUnderlying(
      balanceSheet: PromiseOrValue<string>,
      hifiPool: PromiseOrValue<string>,
      maxBorrowAmount: PromiseOrValue<BigNumberish>,
      underlyingOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    buyHTokenAndRepayBorrow(
      hifiPool: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      maxUnderlyingIn: PromiseOrValue<BigNumberish>,
      hTokenOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    buyHTokenAndRepayBorrowWithSignature(
      hifiPool: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      maxUnderlyingIn: PromiseOrValue<BigNumberish>,
      hTokenOut: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositCollateral(
      balanceSheet: PromiseOrValue<string>,
      collateral: PromiseOrValue<string>,
      depositAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositCollateralWithSignature(
      balanceSheet: PromiseOrValue<string>,
      collateral: PromiseOrValue<string>,
      depositAmount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureCollateral: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositUnderlyingAndMintHTokenAndAddLiquidity(
      hifiPool: PromiseOrValue<string>,
      depositAmount: PromiseOrValue<BigNumberish>,
      underlyingOffered: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositUnderlyingAndMintHTokenAndAddLiquidityWithSignature(
      hifiPool: PromiseOrValue<string>,
      depositAmount: PromiseOrValue<BigNumberish>,
      underlyingOffered: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositUnderlyingAndRepayBorrow(
      hToken: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      underlyingAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositUnderlyingAndRepayBorrowWithSignature(
      hToken: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      underlyingAmount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    redeem(
      hToken: PromiseOrValue<string>,
      hTokenAmount: PromiseOrValue<BigNumberish>,
      underlyingAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    redeemWithSignature(
      hToken: PromiseOrValue<string>,
      hTokenAmount: PromiseOrValue<BigNumberish>,
      underlyingAmount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureHToken: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeLiquidity(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeLiquidityAndRedeem(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeLiquidityAndRedeemWithSignature(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureLPToken: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeLiquidityAndWithdrawUnderlying(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      withdrawAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeLiquidityAndWithdrawUnderlyingWithSignature(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      withdrawAmount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureLPToken: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeLiquidityWithSignature(
      hifiPool: PromiseOrValue<string>,
      poolTokensBurned: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureLPToken: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sellHToken(
      hifiPool: PromiseOrValue<string>,
      hTokenIn: PromiseOrValue<BigNumberish>,
      minUnderlyingOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sellHTokenWithSignature(
      hifiPool: PromiseOrValue<string>,
      hTokenIn: PromiseOrValue<BigNumberish>,
      minUnderlyingOut: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureHToken: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sellUnderlying(
      hifiPool: PromiseOrValue<string>,
      underlyingIn: PromiseOrValue<BigNumberish>,
      minHTokenOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sellUnderlyingAndRepayBorrow(
      hifiPool: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      underlyingIn: PromiseOrValue<BigNumberish>,
      minHTokenOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sellUnderlyingAndRepayBorrowWithSignature(
      hifiPool: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      underlyingIn: PromiseOrValue<BigNumberish>,
      minHTokenOut: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sellUnderlyingWithSignature(
      hifiPool: PromiseOrValue<string>,
      underlyingIn: PromiseOrValue<BigNumberish>,
      minHTokenOut: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      signatureUnderlying: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawCollateral(
      balanceSheet: PromiseOrValue<string>,
      collateral: PromiseOrValue<string>,
      withdrawAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawCollateralAndUnwrapWeth(
      weth: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      withdrawAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    wrapEthAndDepositCollateral(
      weth: PromiseOrValue<string>,
      balanceSheet: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
