/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IHifiPoolRegistry,
  IHifiPoolRegistryInterface,
} from "../../contracts/IHifiPoolRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IHifiPool",
        name: "pool",
        type: "address",
      },
    ],
    name: "HifiPoolRegistry__PoolAlreadyTracked",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "contract IHifiPool",
        name: "pool",
        type: "address",
      },
    ],
    name: "HifiPoolRegistry__PoolNotTracked",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IHifiPool",
        name: "pool",
        type: "address",
      },
    ],
    name: "TrackPool",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oldOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "TransferOwnership",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract IHifiPool",
        name: "pool",
        type: "address",
      },
    ],
    name: "UntrackPool",
    type: "event",
  },
  {
    inputs: [],
    name: "_renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "_transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "pools",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IHifiPool",
        name: "pool",
        type: "address",
      },
    ],
    name: "trackPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IHifiPool",
        name: "pool",
        type: "address",
      },
    ],
    name: "untrackPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHifiPoolRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IHifiPoolRegistryInterface {
    return new utils.Interface(_abi) as IHifiPoolRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHifiPoolRegistry {
    return new Contract(address, _abi, signerOrProvider) as IHifiPoolRegistry;
  }
}
