name: "Deploy: HToken and HifiPool"

env:
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}
  POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}

on:
  workflow_dispatch:
    inputs:
      balance-sheet:
        description: "Address of the BalanceSheet contract"
        required: true
      chain:
        description: "Chain name in lowercase"
        required: true
      confirmations:
        default: "2"
        description: "Number of block confirmations to wait before attempting verification"
        required: false
      fintroller:
        description: "Address of the Fintroller contract"
        required: true
      h-token-maturity:
        description: "Unix timestamp for when the hToken matures"
        required: true
      h-token-name:
        description: "ERC-20 name of the hToken"
        required: true
      h-token-symbol:
        description: "ERC-20 symbol of the hToken"
        required: true
      hifi-pool-registry:
        description: "Address of the HifiPoolRegistry contract"
        required: true
      new-owner:
        default: ""
        description: "Address of new owner to set the deployed hToken contract to"
        required: false
      underlying:
        description: "Address of the underlying ERC-20 contract"
        required: true

jobs:
  deploy-and-verify:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"
        with:
          ref: "main"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: "Build the TypeScript packages"
        run: "yarn build"

      - name: "Compile the contracts and generate TypeChain bindings"
        run: "yarn compile:sol"

      - name: "Build the TypeChain bindings"
        run: "yarn generate:types"

      - name: "Deploy HToken"
        id: "deploy-h-token"
        run: >-
          yarn workspace @hifi/protocol hardhat
          deploy:contract:h-token --network "${{ github.event.inputs.chain }}"
          --balance-sheet "${{ github.event.inputs.balance-sheet }}"
          --fintroller "${{ github.event.inputs.fintroller }}"
          --maturity "${{ github.event.inputs.h-token-maturity }}"
          --name "${{ github.event.inputs.h-token-name }}"
          --new-owner "${{ github.event.inputs.new-owner }}"
          --symbol "${{ github.event.inputs.h-token-symbol }}"
          --underlying "${{ github.event.inputs.underlying }}"
          --confirmations "${{ github.event.inputs.confirmations }}"
          --print true
          --set-output true
          --verify true

      - name: "Deploy HifiPool"
        id: "deploy-hifi-pool"
        run: >-
          yarn workspace @hifi/amm hardhat
          deploy:contract:hifi-pool --network "${{ github.event.inputs.chain }}"
          --h-token "${{ steps.deploy-h-token.outputs.h-token }}"
          --hifi-pool-registry "${{ github.event.inputs.hifi-pool-registry }}"
          --name "${{ github.event.inputs.h-token-name }} Pool"
          --symbol "${{ github.event.inputs.h-token-symbol }}LP"
          --confirmations "${{ github.event.inputs.confirmations }}"
          --print true
          --verify true
