name: "Init: Add Liquidity"

env:
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}
  POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}

on:
  workflow_dispatch:
    inputs:
      chain:
        description: "Chain name in lowercase"
        required: true
      hifi-pool:
        description: "Pool address"
        required: true
      pool-underlying-amount:
        description: "Amount of underlying to add as liquidity in the pool"
        required: true
      ref:
        default: "main"
        description: "Git ref to checkout"
        required: false
      supply-underlying-amount:
        description: "Amount of underlying to supply in exchange for hTokens"
        required: true

jobs:
  add-liquidity:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: "Setup Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: "Build the TypeScript packages"
        run: "yarn build"

      - name: "Compile the contracts and generate TypeChain bindings"
        run: "yarn compile:sol"

      - name: "Build the TypeChain bindings"
        run: "yarn build:types"

      - name: "Add liquidity"
        id: "init"
        run: >-
          yarn workspace @hifi/amm hardhat
          init:add-liquidity --network "${{ github.event.inputs.chain }}"
          --hifi-pool "${{ github.event.inputs.hifi-pool }}"
          --pool-underlying-amount "${{ github.event.inputs.pool-underlying-amount }}"
          --supply-underlying-amount "${{ github.event.inputs.supply-underlying-amount }}"
