/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface YieldSpaceMockInterface extends utils.Interface {
  functions: {
    "doGetYieldExponent(uint256,uint256)": FunctionFragment;
    "doHTokenInForUnderlyingOut(uint256,uint256,uint256,uint256)": FunctionFragment;
    "doHTokenOutForUnderlyingIn(uint256,uint256,uint256,uint256)": FunctionFragment;
    "doUnderlyingInForHTokenOut(uint256,uint256,uint256,uint256)": FunctionFragment;
    "doUnderlyingOutForHTokenIn(uint256,uint256,uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "doGetYieldExponent"
      | "doHTokenInForUnderlyingOut"
      | "doHTokenOutForUnderlyingIn"
      | "doUnderlyingInForHTokenOut"
      | "doUnderlyingOutForHTokenIn"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "doGetYieldExponent",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "doHTokenInForUnderlyingOut",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "doHTokenOutForUnderlyingIn",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "doUnderlyingInForHTokenOut",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "doUnderlyingOutForHTokenIn",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "doGetYieldExponent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doHTokenInForUnderlyingOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doHTokenOutForUnderlyingIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doUnderlyingInForHTokenOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doUnderlyingOutForHTokenIn",
    data: BytesLike
  ): Result;

  events: {};
}

export interface YieldSpaceMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: YieldSpaceMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    doGetYieldExponent(
      timeToMaturity: PromiseOrValue<BigNumberish>,
      g: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { a: BigNumber }>;

    doHTokenInForUnderlyingOut(
      normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
      hTokenReserves: PromiseOrValue<BigNumberish>,
      normalizedUnderlyingOut: PromiseOrValue<BigNumberish>,
      timeToMaturity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { hTokenIn: BigNumber }>;

    doHTokenOutForUnderlyingIn(
      normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
      hTokenReserves: PromiseOrValue<BigNumberish>,
      normalizedUnderlyingIn: PromiseOrValue<BigNumberish>,
      timeToMaturity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { hTokenOut: BigNumber }>;

    doUnderlyingInForHTokenOut(
      hTokenReserves: PromiseOrValue<BigNumberish>,
      normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
      hTokenOut: PromiseOrValue<BigNumberish>,
      timeToMaturity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { normalizedUnderlyingIn: BigNumber }>;

    doUnderlyingOutForHTokenIn(
      hTokenReserves: PromiseOrValue<BigNumberish>,
      normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
      hTokenIn: PromiseOrValue<BigNumberish>,
      timeToMaturity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { normalizedUnderlyingOut: BigNumber }>;
  };

  doGetYieldExponent(
    timeToMaturity: PromiseOrValue<BigNumberish>,
    g: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  doHTokenInForUnderlyingOut(
    normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
    hTokenReserves: PromiseOrValue<BigNumberish>,
    normalizedUnderlyingOut: PromiseOrValue<BigNumberish>,
    timeToMaturity: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  doHTokenOutForUnderlyingIn(
    normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
    hTokenReserves: PromiseOrValue<BigNumberish>,
    normalizedUnderlyingIn: PromiseOrValue<BigNumberish>,
    timeToMaturity: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  doUnderlyingInForHTokenOut(
    hTokenReserves: PromiseOrValue<BigNumberish>,
    normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
    hTokenOut: PromiseOrValue<BigNumberish>,
    timeToMaturity: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  doUnderlyingOutForHTokenIn(
    hTokenReserves: PromiseOrValue<BigNumberish>,
    normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
    hTokenIn: PromiseOrValue<BigNumberish>,
    timeToMaturity: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    doGetYieldExponent(
      timeToMaturity: PromiseOrValue<BigNumberish>,
      g: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doHTokenInForUnderlyingOut(
      normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
      hTokenReserves: PromiseOrValue<BigNumberish>,
      normalizedUnderlyingOut: PromiseOrValue<BigNumberish>,
      timeToMaturity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doHTokenOutForUnderlyingIn(
      normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
      hTokenReserves: PromiseOrValue<BigNumberish>,
      normalizedUnderlyingIn: PromiseOrValue<BigNumberish>,
      timeToMaturity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doUnderlyingInForHTokenOut(
      hTokenReserves: PromiseOrValue<BigNumberish>,
      normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
      hTokenOut: PromiseOrValue<BigNumberish>,
      timeToMaturity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doUnderlyingOutForHTokenIn(
      hTokenReserves: PromiseOrValue<BigNumberish>,
      normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
      hTokenIn: PromiseOrValue<BigNumberish>,
      timeToMaturity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    doGetYieldExponent(
      timeToMaturity: PromiseOrValue<BigNumberish>,
      g: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doHTokenInForUnderlyingOut(
      normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
      hTokenReserves: PromiseOrValue<BigNumberish>,
      normalizedUnderlyingOut: PromiseOrValue<BigNumberish>,
      timeToMaturity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doHTokenOutForUnderlyingIn(
      normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
      hTokenReserves: PromiseOrValue<BigNumberish>,
      normalizedUnderlyingIn: PromiseOrValue<BigNumberish>,
      timeToMaturity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doUnderlyingInForHTokenOut(
      hTokenReserves: PromiseOrValue<BigNumberish>,
      normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
      hTokenOut: PromiseOrValue<BigNumberish>,
      timeToMaturity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doUnderlyingOutForHTokenIn(
      hTokenReserves: PromiseOrValue<BigNumberish>,
      normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
      hTokenIn: PromiseOrValue<BigNumberish>,
      timeToMaturity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    doGetYieldExponent(
      timeToMaturity: PromiseOrValue<BigNumberish>,
      g: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    doHTokenInForUnderlyingOut(
      normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
      hTokenReserves: PromiseOrValue<BigNumberish>,
      normalizedUnderlyingOut: PromiseOrValue<BigNumberish>,
      timeToMaturity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    doHTokenOutForUnderlyingIn(
      normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
      hTokenReserves: PromiseOrValue<BigNumberish>,
      normalizedUnderlyingIn: PromiseOrValue<BigNumberish>,
      timeToMaturity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    doUnderlyingInForHTokenOut(
      hTokenReserves: PromiseOrValue<BigNumberish>,
      normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
      hTokenOut: PromiseOrValue<BigNumberish>,
      timeToMaturity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    doUnderlyingOutForHTokenIn(
      hTokenReserves: PromiseOrValue<BigNumberish>,
      normalizedUnderlyingReserves: PromiseOrValue<BigNumberish>,
      hTokenIn: PromiseOrValue<BigNumberish>,
      timeToMaturity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
