/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  IBalanceSheetUpgraded,
  IBalanceSheetUpgradedInterface,
} from "../../../../contracts/test/BalanceSheetUpgraded.sol/IBalanceSheetUpgraded";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [],
    name: "getLastBlockNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "setLastBlockNumber",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBalanceSheetUpgraded__factory {
  static readonly abi = _abi;
  static createInterface(): IBalanceSheetUpgradedInterface {
    return new utils.Interface(_abi) as IBalanceSheetUpgradedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBalanceSheetUpgraded {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IBalanceSheetUpgraded;
  }
}
