/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBalanceSheetUpgraded,
  IBalanceSheetUpgradedInterface,
} from "../../../../contracts/test/BalanceSheetUpgraded.sol/IBalanceSheetUpgraded";

const _abi = [
  {
    inputs: [],
    name: "getLastBlockNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "setLastBlockNumber",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBalanceSheetUpgraded__factory {
  static readonly abi = _abi;
  static createInterface(): IBalanceSheetUpgradedInterface {
    return new Interface(_abi) as IBalanceSheetUpgradedInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBalanceSheetUpgraded {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IBalanceSheetUpgraded;
  }
}
